# Generated by Django 5.1.1 on 2024-09-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stop_type', models.CharField(choices=[('taxi', 'Taxi'), ('bus', 'Bus')], max_length=4)),
                ('start_photo', models.ImageField(upload_to='stops/images/')),
                ('end_photo', models.ImageField(upload_to='stops/images/')),
                ('commune', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
        ),
    ]
