# Generated by Django 5.1.1 on 2024-09-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0003_marker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
