# Generated by Django 5.1.1 on 2024-09-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0004_delete_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignetrajet',
            name='debut_nom',
            field=models.CharField(default='Début', max_length=100),
        ),
        migrations.AddField(
            model_name='lignetrajet',
            name='fin_nom',
            field=models.CharField(default='Fin', max_length=100),
        ),
    ]
