# Generated by Django 5.1.1 on 2024-09-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0005_lignetrajet_debut_nom_lignetrajet_fin_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignetrajet',
            name='debut_nom',
        ),
        migrations.RemoveField(
            model_name='lignetrajet',
            name='fin_nom',
        ),
        migrations.AddField(
            model_name='lignetrajet',
            name='trajet',
            field=models.CharField(default='', max_length=100),
        ),
    ]
